spring:
  http:                   # HTTP 인코딩
    encoding:
      charset: UTF-8      # 요청/응답의 인코딩
      enabled: true       # 인코딩 지원 활성화
      force: true         # 구성된 인코딩을 강제 활성화
  mustache:
    suffix: .html
  output:
    ansi:
      enabled: always     # 콘솔 창에 출력되는 로깅 메세지를 색으로 구분해서 출력
---
spring:
  profiles:
    active: Mariadb   # 기본 데이터베이스 환경 선택
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:                         # DB Connection이 증가하여 DB와의 연결이 끊어지는 문제가 발생하여 'hikariCP'값 셋팅(딱히 무리있는 작업이 없는데 끊어져버림..-,-)
      maxLifetime: 700000           # 커넥션의 최대 유지 시간을 밀리초 단위로 설정(이 시간이 지난 커넥션 중에서 사용중인 커넥션은 종료된 이후에 풀에서 제거)
      connection-timeout: 30000     # 풀에서 커넥션을 구할 때 대기 시간을 밀리초 단위로 지정(대기시간 안에 구하지 못하면 익셉션이 발생)
      validation-timeout: 30000     # 커넥션이 유효한지 검사할 때 대기 시간을 지정
---
spring:
  profiles: Mariadb   # 데이터베이스
  datasource:
    #    url: jdbc:mariadb://codedot.co.kr:3306/portfolio?characterEncoding=UTF-8   # 운영 데이터베이스
    #    username: portfolio
    #    password: tmdghks05)%
    url: jdbc:mariadb://codedot.co.kr:3306/test_user_01?characterEncoding=UTF-8  # 테스트 데이터베이스
    username: test_user_01
    password: dl945pa