spring:
  http:               # HTTP 인코딩
    encoding:
      charset: UTF-8  # 요청/응답의 인코딩
      enabled: true   # 인코딩 지원 활성화
      force: true     # 구성된 인코딩을 강제 활성화
  mustache:
    suffix: .html     # 템플릿 확장자 변경
---
spring:
  profiles:
    active: Mariadb   # 기본 데이터베이스 환경 선택
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
---
spring:
  profiles: Mariadb   # 데이터베이스
  datasource:
#    url: jdbc:mariadb://218.237.179.69:3306/portfolio?characterEncoding=UTF-8   # 운영 데이터베이스
#    username: portfolio
#    password: tmdghks05)%
    url: jdbc:mariadb://218.237.179.69:3306/test_user_01?characterEncoding=UTF-8  # 테스트 데이터베이스
    username: test_user_01
    password: dl945pa

